### ISSUE TITLE
Emit dragStart and dragEnd

### ISSUE THREAD

**Issue by curran** [replit/codemirror-interact#14]
As an application developer using this library, I want to be able to know when a drag interaction starts and when a drag interaction ends (for the number dragger), so that I can change my application's behavior to allow more frequent updates during drag (the issue I'm working on for reference: [Interactive Code Widgets](https://github.com/vizhub-core/vzcode/issues/74)).

It seems possible to expose these from internals, starting here https://github.com/replit/codemirror-interact/blob/36c0eecf9d9825b7ad3ad1b9d54e7b2a1cb90349/src/interact.ts#L242

**Comment by slmjkdbtl** [comment]
Added in v6.3.0!

```js
{
    regexp: /-?\b\d+\.?\d*\b/g,
    cursor: 'ew-resize',
    onDragStart: (text, setText, e) => {
        console.log(text)
    },
}

```

**Comment by curran** [comment]
Oh wow nice! Thank you so much!

**Comment by curran** [comment]
@slmjkdbtl The current latest version is `"version": "6.2.0",` in the [most recent commit to master](https://github.com/replit/codemirror-interact/blob/36c0eecf9d9825b7ad3ad1b9d54e7b2a1cb90349/package.json). Did the publishing not happen?

**Comment by slmjkdbtl** [comment]
Yes for sure, pushed!

**Comment by curran** [comment]
Excellent! Thank you so much!

Another "nice to have", while we're at it, would be a GitHub "Release", which would show up here https://github.com/replit/codemirror-interact/releases . GitHub has a really nice "generate release notes" feature that sums up which PRs go into each release. Setting this up should only take a few button clicks as it's largely automated.

Thanks so much for the work on this! I'm really loving this extension. It's amazing when paired with hot reloading.

**Comment by sergeichestakov** [comment]
yes agreed. definitely some work we could do to cleanup how we do releases on most of our open source repos. we didn't expect some of these to be as popular as they were so we hadn't gotten around to it.
